name: Swift

on: [ pull_request ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.4.0"
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test --filter "SolanaSwiftAutoTests"
