name: Swift

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.4.0"
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test --filter "SolanaSwiftAutoTests"
